# docker-compose file to launch the LC-Server behind an NGINX reverse proxy
version: "3"
services:
  nginx:
    build: ./nginx
    container_name: server_nginx_1
    links: 
      - lc-server:lc-server
    ports: 
      - "8080:80"
  lc-server:
    build: ./
    container_name: server_lc-server_1
    deploy:
      resources:
        limits:
          cpus: '1'
    ports:
      - "3000:3000"